### ISSUE TITLE
Error ubuntu 20.04

### ISSUE THREAD

**Issue by jvazservices** [mariosemes/PornHub-downloader-python#25]
Running startup checks...
Database exists.
PornHub url validated.
This is a PORNSTAR url,
and the URL is existing.
Traceback (most recent call last):
  File "phdler.py", line 55, in <module>
    main()
  File "phdler.py", line 21, in main
    add_check(sys.argv[2])
  File "/home/xxx/PornHub-downloader-python-master/functions.py", line 88, in add_check
    add_item(name_check)
  File "/home/xxx/PornHub-downloader-python-master/functions.py", line 273, in add_item
    item_name = get_item_name(item_type, name_check)
  File "/home/xxx/PornHub-downloader-python-master/functions.py", line 102, in get_item_name
    title = finder.find(class_='name').text.replace('\n', '').strip()
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by jvazservices** [comment]
ok
