### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by Kizero1998** [mariosemes/PornHub-downloader-python#27]
root@ubuntu:~/PornHub-downloader-python-master# python3 phdler.py add https://www.pornhub.com/channels/mia-khalifa
Running startup checks...
Database exists.
PornHub url validated.
This is a CHANNEL url,
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f33bb285bb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /channels/mia-khalifa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f33bb285bb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phdler.py", line 55, in <module>
    main()
  File "phdler.py", line 21, in main
    add_check(sys.argv[2])
  File "/root/PornHub-downloader-python-master/functions.py", line 88, in add_check
    add_item(name_check)
  File "/root/PornHub-downloader-python-master/functions.py", line 270, in add_item
    ph_alive_check(name_check)
  File "/root/PornHub-downloader-python-master/functions.py", line 68, in ph_alive_check
    requested = requests.get(url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /channels/mia-khalifa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f33bb285bb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by mariosemes** [comment]
The development of this tools is deprecated.
Feel free to fork it and keep on developing it.
