### ISSUE TITLE
AttrubuteError: when trying to use add option.

### ISSUE THREAD

**Issue by try1ngmybest** [mariosemes/PornHub-downloader-python#45]
`$ python3 phdler.py add https://www.pornhub.com/channels/mia-khalifa`
will return the error
```
Running startup checks...
Database exists.
PornHub url validated.
This is a CHANNEL url,
and the URL is existing.
Traceback (most recent call last):
  File "phdler.py", line 55, in <module>
    main()
  File "phdler.py", line 21, in main
    add_check(sys.argv[2])
  File "/home/<username>/PornHub-downloader-python/functions.py", line 88, in add_check
    add_item(name_check)
  File "/home/<username>/PornHub-downloader-python/functions.py", line 273, in add_item
    item_name = get_item_name(item_type, name_check)
  File "/home/<username>/PornHub-downloader-python/functions.py", line 105, in get_item_name
    title = finder.find(class_='title').text.replace('\n', '').strip()
AttributeError: 'NoneType' object has no attribute 'find'

```
using python 3.8.5
using package versions from requirements.txt

**Comment by mariosemes** [comment]
The development of this tools is deprecated.
Feel free to fork it and keep on developing it.
